In [1]:
team_name = "金州勇士隊"
wins = 21
losses = 4
win_percentage = 0.84
is_on_winning_streak = True

golden_state_warriors = {
    "team_name": team_name,
    "wins": wins,
    "losses": losses,
    "win_percentage": win_percentage,
    "is_on_winning_streak": is_on_winning_streak
}

# 利用鍵值選擇元素
print(golden_state_warriors["team_name"])
print(golden_state_warriors["wins"])
print(golden_state_warriors["losses"])
print(golden_state_warriors["win_percentage"])
print(golden_state_warriors["is_on_winning_streak"])

金州勇士隊
21
4
0.84
True


In [2]:
km_list = [21, 42.195]
km_to_mile = 0.621371192
mile_list = km_list * km_to_mile


TypeError: can't multiply sequence by non-int of type 'float'

In [4]:
import numpy

km_list=[21,42.195]
km_array=numpy.array(km_list)
print(type(km_array))
km_to_mile=0.621371192
mile_array=km_array*km_to_mile
print(mile_array)

<class 'numpy.ndarray'>
[ 13.04879503  26.21875745]


In [5]:
import numpy as np

km_list = [21, 42.195]
km_array = np.array(km_list)
print(type(km_array))
km_to_mile = 0.621371192
mile_array = km_array * km_to_mile
print(mile_array)

<class 'numpy.ndarray'>
[ 13.04879503  26.21875745]


In [11]:
import numpy as np

my_np_array=np.array([1,True])
print(my_np_array.dtype)
my_np_array=np.array([1,True,"one"])
print(my_np_array.dtype)

int32
<U11


In [14]:
import numpy as np

my_np_array=np.array([1,2,3,4])
print(my_np_array)
print(my_np_array**2)

my_2d_array=np.array([[1,3],
                      [2,4]])
print(my_2d_array)
print(my_2d_array**2)

[1 2 3 4]
[ 1  4  9 16]
[[1 3]
 [2 4]]
[[ 1  9]
 [ 4 16]]


In [17]:
import numpy as np

my_np_array=np.array([1,2,3,4])
print(my_np_array[0])

my_2d_array=np.array([[1,3],
                      [2,4]])
print(my_2d_array[0,1])  #[列，欄]

1
3


In [30]:
import numpy as np

my_np_array=np.array([1,2,3,4])
filter=my_np_array<2
print(my_np_array[filter])

my_2d_array=np.array([[1,3],
                     [2,4]])
filter=my_2d_array>=2
print(my_2d_array[filter])
filter

[1]
[3 2 4]


array([[False,  True],
       [ True,  True]], dtype=bool)

In [33]:
import numpy as np

my_np_array=np.array([1,2,3,4])
print(my_np_array.size)  #how many items
print(my_np_array.shape)  #how many columns?

my_2d_array=np.array([[1,3], 
                      [2,4]])
print(my_2d_array.size)
print(my_2d_array.shape)

4
(4,)
4
(2, 2)


In [40]:
import pandas as pd

name = ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"]
age = [19, 21, 20, 19, 21, 17, 30, 36, 90]

straw_hat_dict={"name":name, 
                "age":age
}

#type(straw_hat_dict)

straw_hat_df=pd.DataFrame(straw_hat_dict)
print(type(straw_hat_df))
straw_hat_df

<class 'pandas.core.frame.DataFrame'>


age               name
0   19    Monkey D. Luffy
1   21       Roronoa Zoro
2   20               Nami
3   19              Usopp
4   21     Vinsmoke Sanji
5   17  Tony Tony Chopper
6   30         Nico Robin
7   36             Franky
8   90              Brook

In [42]:
import pandas as pd

name = ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"]
age = [19, 21, 20, 19, 21, 17, 30, 36, 90]
is_male = [True, True, False, True, True, True, False, True, True]

straw_hat_dict={"name":name, 
                "age":age, 
                "is_male":is_male
               }

straw_hat_df=pd.DataFrame(straw_hat_dict)

print(straw_hat_df.dtypes)

age         int64
is_male      bool
name       object
dtype: object


In [50]:
import pandas as pd

name = ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"]
age = [19, 21, 20, 19, 21, 17, 30, 36, 90]
is_male = [True, True, False, True, True, True, False, True, True]

straw_hat_dict={"name":name, 
                "age":age, 
                "is_male":is_male
               }

straw_hat_df=pd.DataFrame(straw_hat_dict)

#print(straw_hat_df.ix[0,:])
#print(straw_hat_df.ix[:,"name"])
print(straw_hat_df.ix[0,"name"])

Monkey D. Luffy


In [57]:
import pandas as pd

name = ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"]
age = [19, 21, 20, 19, 21, 17, 30, 36, 90]
is_male = [True, True, False, True, True, True, False, True, True]

straw_hat_dict={"name":name, 
                "age":age, 
                "is_male":is_male
               }

straw_hat_df=pd.DataFrame(straw_hat_dict)

filter=straw_hat_df.ix[:,"age"]<=30
straw_hat_df[filter]

filter=straw_hat_df.ix[:,"is_male"]==False
straw_hat_df[filter]

age is_male        name
2   20   False        Nami
6   30   False  Nico Robin

In [62]:
import pandas as pd

name = ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"]
age = [19, 21, 20, 19, 21, 17, 30, 36, 90]
is_male = [True, True, False, True, True, True, False, True, True]

straw_hat_dict={"name":name, 
                "age":age, 
                "is_male":is_male
               }

straw_hat_df=pd.DataFrame(straw_hat_dict)

print(straw_hat_df.shape)
print(straw_hat_df.describe())
print(straw_hat_df.head(3))
print(straw_hat_df.tail(3))
print(straw_hat_df.columns)
print(straw_hat_df.index)


(9, 3)
             age
count   9.000000
mean   30.333333
std    23.205603
min    17.000000
25%    19.000000
50%    21.000000
75%    30.000000
max    90.000000
   age is_male             name
0   19    True  Monkey D. Luffy
1   21    True     Roronoa Zoro
2   20   False             Nami
   age is_male        name
6   30   False  Nico Robin
7   36    True      Franky
8   90    True       Brook
Index(['age', 'is_male', 'name'], dtype='object')
RangeIndex(start=0, stop=9, step=1)


In [63]:
nba_divs = ["大西洋組", "中央組", "東南組", "西北組", "太平洋組", "西南組"]

print(nba_divs[0])
print(nba_divs[1])
print(nba_divs[2])
print(nba_divs[3])
print(nba_divs[4])
print(nba_divs[5])

大西洋組
中央組
東南組
西北組
太平洋組
西南組


In [64]:
nba_divs = ["大西洋組", "中央組", "東南組", "西北組", "太平洋組", "西南組"]

#一直複製貼上時可以使用迴圈
for div in nba_divs:
    print(div)

大西洋組
中央組
東南組
西北組
太平洋組
西南組


In [71]:
x=0
for i in range(1,101):
    x=x+i
print(x)
print(i)

5050
100
